### ISSUE TITLE
Miami large area unwrap errors -- lets try to get rid of them

### ISSUE THREAD

**Issue by falkamelung** [geodesymiami/MiNoPy#54] opened 2021-12-19 00:05 UTC
I was hoping to process the entire area (Coconut Grove to Surfside) for different time periods (first 201901-202106, until collapse) but was not able to get rid of the unwrap error. Once we have fixed the bugs we should try again with different networks. This ought to be possible and could be a good example for the paper. Here the area and the results:

```
###### Miami large with reference in North Miami   ##############
mintpy.subset.lalo                    = 25.725:25.91,-80.242:-80.115             # large: Coconut Grove to Surfside
mintpy.reference.lalo                 = 25.8914,-80.1583                         # North Miami near Keystone islands

```

<img width="649" alt="image" src="https://user-images.githubusercontent.com/11162588/146658730-6e2d218c-6552-4340-8f2b-ecc2ca792272.png">

<img width="1488" alt="image" src="https://user-images.githubusercontent.com/11162588/146658845-ddecd725-b9d0-46c7-bbee-450d45232005.png">

**Comment by mirzaees** [comment] 2022-01-09 03:08
@falkamelung , Correcting unwrap error is not the purpose of minopy. For each case study there are parameters for unwrapping and mintpy unwrap error correction to play with and improve the results but this is not a bug. please close the issue if there is no related bug you found

**Comment by mirzaees** [comment] 2022-04-20 15:22
I am closing this issue

**Closed by mirzaees** 2022-04-20 15:22 UTC
