### ISSUE TITLE
All velocity values are zero, when the "minopy.interferograms.type" is set to "single_reference"

### ISSUE THREAD

**Issue by yuluenter** [geodesymiami/MiNoPy#64] opened 2022-02-26 09:22 UTC
Hi everyone, I met an issues. When I use the new version in 2022, and try to use the "single_reference" as the interferograms type, I got the result that the velocity values of sample dataset(PichinchaSenDT142) ​​are all 0, as shown in the image below.
![velocity](https://user-images.githubusercontent.com/36024012/155837799-98336ebb-8979-4305-9090-669ee02c8ff4.jpg)

But when I use the November 2021 version, the same dataset is able to invert the correct results.

**Comment by mirzaees** [comment] 2022-03-02 17:42
Hi @yuluenter 
Sorry I forgot about this issue 

The problem is that mintpy does not invert for non redundant interferograms with weighted option. so I suggest to set following to 'no' and run again from invert_network

https://github.com/insarlab/MintPy/blob/575f32b14080d93b4b4319576573e9723909ab0a/mintpy/defaults/smallbaselineApp.cfg#L164

**Comment by mirzaees** [comment] 2022-03-09 15:12
@yuluenter This problem is fixed now in mintpy, I am closing the issue

**Closed by mirzaees** 2022-03-09 15:12 UTC
